### PR TITLE
Issue512

### LINKED ISSUE #512: Update the CONTRIBUTING.md file
### Feature Description

At minimum, we need to add JS docs to CONTRIBUTING.md.

Having someone new, especially who doesn't have very much technical or hugo/web-dev experience ensure that all the steps and general guidance in that doc is useful (giving some type of feedback probably on this issue or on their PR), would probably help ensure it's well documented from a new person perspective.

I'd imagine some documentation around the testing stuff would be helpful as well. @TheHesster had expressed some potential interest in this part (tests), so if you'd like to tackle that, that'd be awesome (no pressure though if you don't want to).

### Reference to Feature

* [Mention of adding JS location to docs](https://matrix.to/#/!rDlEtonuSythLzmxQL:jupiterbroadcasting.com/$ukUhoSh_tFeDxWvWWycRH1NsMiDjQTqlG0o-DE7oIwI)
* [TheHesster expressing interest](https://matrix.to/#/!rDlEtonuSythLzmxQL:jupiterbroadcasting.com/$dI3jbuYyWq8yz7y-d--1uSfrYvdeb_2_I0p3er4mFSQ)

### PR DESCRIPTION
**Pull request by 1701home**
Closes #512

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
So I'm thinking this one will sit on hold for now until #529 is merged. Then we can work on making sure only the contributing changes are in this PR

**Comment by gerbrent** [comment]
@1701home - Can you be more descriptive in the future with your PR titles and also commit messages?

I'm struggling to really wrap my head around an initial understanding of what this PR is solving, esp since there are seemingly some scraper commits mixed in aswell?

I do see #512 referenced, but that too is a little vague.
Thank you!

For now, a quick description here of what this PR is attempting to accomplish would be really helpful.

**Comment by gerbrent** [comment]
No problem @1701home ! Nightmares are ok, as long as you feel you're getting support and guidance on how to improve in those areas, which it sounds like you are at that's a complete success! We're all here to learn a little something, be it how to do open source collaboratively,  improving our git chops, learning a new language or the GH interface or anything else!

So, please, no worries... happy you're making progress on the PR and thank you for submitting your ideas and talents!

**Comment by 1701home** [comment]
Thank you very much, @gerbrent ! It is very nice to have people like @CGBassPlayer and yourself to help show the way. I really enjoy doing this, too. I am excited to see what I can do with my new tools this weekend!

**Pull request closed without merging**
