### PR TITLE
`develop` -> `main` - testing w/ #400

### PR DESCRIPTION
**Pull request by gerbrent**
only https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/400 in this PR.

`develop` -> `main` to test workflow as discussed in #432

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
Woo! being the Guinea Pig!

**Comment by elreydetoda** [comment]
@CGBassPlayer , everything still look good to you? (Just want to make sure)

**Comment by elreydetoda** [comment]
Actually, looks like they're exactly the same (as expected :grin: )

image

Link you can use to look at it :grin: 

https://github.com/CGBassPlayer/jupiterbroadcasting.com/compare/bugfix/episode-layout...JupiterBroadcasting:jupiterbroadcasting.com:develop?expand=1

**Review by elreydetoda — APPROVED** [review]
LGTM based on this: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/433#issuecomment-1260149902

**Comment by elreydetoda** [comment]
I don't know why the branch was deleted...I didn't click the button, but I've restored it :sweat_smile:

**Comment by gerbrent** [comment]
haha, guess we have to solve this one ; )
I imagine it'll be different when the default is set to `develop`, and no PR ever goes from `main`-> `develop`

image


Will work on that soon!

**Comment by CGBassPlayer** [comment]
I know there are ways to protect a branch. All I know about it is that you can apply rules about branch (PR required, deployments need to be successful, etc). I found some [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) about it, but I have never done this myself

**Comment by CGBassPlayer** [comment]
So once I got home to the non-mobile version of GitHub, I managed to find it. If you go to the repo's settings -> Code and Automation -> Branches and you guys can setup branch rules and assign them to the appropriate branches. I might try to play with this on a test repo and report back what I think would be helpful

**Comment by elreydetoda** [comment]
> haha, guess we have to solve this one ; ) I imagine it'll be different when the default is set to `develop`, and no PR ever goes from `main`-> `develop`
> 
> image
> 
> Will work on that soon!

So, it looks like your assumption was right, but now I can delete main :sweat_smile: 

image

You should be able to do something like this at bare minimum for develop

image

Then a no checks one for main, because this will prevent force pushes and deletions

image

This would be the ideal options (IMO) for develop, but we can ease into that if we want :upside_down_face: 

image

Ideally the "production" environment would be used for keeping your production secrets (i.e. ssh private key for connecting to the server) and it would require manual approval for deployment (similar to the infra repo's eventual setup), but that'd break how we currently use the scraper for auto-deployments.

At minimum though it should be set for protected branches for the deployment branches (after setting up the protected branches above).

**Pull request merged**
