### PR TITLE
adding test for checking matrix well_known file

### PR DESCRIPTION
**Pull request by elreydetoda**
should prevent #381 from happening again.

### CODE REVIEW

**Comment by gerbrent** [comment]
nice one!

**Comment by gerbrent** [comment]
helps avoid #381

**Comment by gerbrent** [comment]
looks like some E2E errors. I'll check the assumed path in the test of `/.well-known/matrix/server`

image


https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8162128923

But there is also another failed test that might relate..

**Comment by gerbrent** [comment]
/.well-known/matrix/server is good:

`curl -I https://www.jupiterbroadcasting.com/.well-known/matrix/server
HTTP/2 200 `

**Comment by elreydetoda** [comment]
Ya...I was just noticing that (I'd expected the E2E tests to run when I submitted my PR, but #385 says why it didn't).

For some reason it looks like it's [not passing the page object right](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8162095907?check_suite_focus=true#step:9:78): `<Page url='about:blank'>`

This is what it [should be passing](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8162095907?check_suite_focus=true#step:9:32): `<Page url='http://localhost:1313/'>`

I don't know why this is happening yet, but everything ran perfectly fine in the local testing environment... :thinking: (still figuring out why it's not working)

[asciicast](https://asciinema.org/a/iVKZ3jCxNFp5hl4cqQ1ND7aSp)

**Comment by elreydetoda** [comment]
I'm even more confused now... 🤦

So...I was doing some testing, and I created 2 more branches off of my #353 PR...

1. was no modification besides adding the new check I'd created & adding the new well known from #382 
2. I pulled all the changes from main and then re-applied my commits with #353 (so it'd effectively be what main would look like after #353 is merged)

Number 1 failed with the same error we're seeing with this PR: https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8163979470?check_suite_focus=true#step:9:28
Number 2 failed with the same error we're seeing with this PR: https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8163879397?check_suite_focus=true#step:9:28

but then things get interesting...I removed the well known file commit to my Number 1 branch, and while it still failed (because the well known file no longer exists) it actually passed in the right object (with the base_domain)!!! :thinking: 
https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8164035325?check_suite_focus=true#step:9:28

**Comment by gerbrent** [comment]
so confusing!! hmmmmm..............

**Comment by gerbrent** [comment]
@elreydetoda and I just spent much time trying to solve this one together, and..... 🥁 drumroll! 🥁 ........ didn't solve it! BLAST.

**Comment by elreydetoda** [comment]
alright...I think I'm starting down the right path to solve this...I've finally been able to replicate it! (locally & in GH actions)

https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8180359800?check_suite_focus=true

(ignore the other error, that's because of the way I'm currently building the container and I'm about to change it to fix that :upside_down_face: :sweat_smile: )

The only consistent change between these situations is that it's not  the hugo binary serving these files...when we're doing the Dockerfile.dev (make dev) locally we're using the hugo file to load the file (which serves it from memory), but when I'm serving it via the container (through nginx or `python3 -m http.server`) I get the error...

I also found that some other people might be having a similar issue with the pytest-playwright library: https://stackoverflow.com/questions/68266451/navigating-to-url-waiting-until-load-python-playwright-issue

I tried their quick fix solution, but it didn't work so still investigating 🧐

**Comment by gerbrent** [comment]
sounds like a potential bug in pytest's playwright library perhaps??

**Pull request merged**
