### PR TITLE
E2E - update Live menu item check address

### PR DESCRIPTION
**Pull request by gerbrent**
update Live menu item check address from `https://jb-live.jupiterbroadcasting.net/` to `/live`

### CODE REVIEW

**Comment by elreydetoda** [comment]
I've already done that in this PR: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/353/files#diff-7dae78a00d8d69422a3bfbde96c7c5d794eede504a0df763853896a1ba1b5ff2R59

It just hasn't been merged yet, but should fix all the E2E tests failing.

**Comment by gerbrent** [comment]
> I've already done that in this PR

right! oops, duplicate effort. I think that's another example of a PR solving more than one distinct feature/bug, thus confusing/hiding the trivial commits (above) with other more complex contributions.

So, lets all try to make PRs that stick to one distinct solution to one distinct problem to avoid duplication of work or extra confusion..

We could merge this simple PR while waiting for review on the more complex and review-awaiting #353

**Comment by elreydetoda** [comment]
> right! oops, duplicate effort. I think that's another example of a PR solving more than one distinct feature/bug, thus confusing/hiding the trivial commits (above) with other more complex contributions.

At the time it was failing because of 2 reasons:
1. the [image used](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/353/files#diff-3e103440521ada06efd263ae09b259e5507e4b8f7408308dc227621ad9efa31eR13)
2. and the [failing test](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/353/files#diff-7dae78a00d8d69422a3bfbde96c7c5d794eede504a0df763853896a1ba1b5ff2R59)

> So, lets all try to make PRs that stick to one distinct solution to one distinct problem to avoid duplication of work or extra confusion..

Also, at the time I'd already mentioned during the intial [PR review](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/325#discussion_r952501248) to use pipenv, and the modification wasn't applied (which means it wasn't using the dependency manger it was supposed to be using). So, in the spirit of your comment [here](https://matrix.to/#/!rDlEtonuSythLzmxQL:jupiterbroadcasting.com/$2roylrhscumUUT_dhoYH510jZGmCcnZ3ddscls6tnOo?via=matrix.org&via=jupiterbroadcasting.com&via=matrix.suorcd.us)

> * would these be better as one PR w multiple commits?

I was just trying to incorporate the other small change to keep from doing multiple small PRs, since you'd mentioned trying to stay away from that in the past.

> We could merge this simple PR while waiting for review on the more complex and review-awaiting https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/353

Ya, we could I don't care either way. I'll have to remove that change from my PR, but it should be fine.

The other consideration is if the GH action messes up again like how it was doing for these GH action runs:
- https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8078153374?check_suite_focus=true#step:4:9 
- https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8078768563?check_suite_focus=true#step:4:9
- https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8080138432?check_suite_focus=true#step:4:9

and we're not using the container image we're using in production (as mentioned [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/353#issue-1354940804)) then we might have more _mysterious_ errors again...

(just mentioning all possibilities for it to fail)

**Comment by gerbrent** [comment]
> since you'd mentioned trying to stay away from that in the past.

really! Hmm.... then clearly I'm the problem ; )
thanks, as always, for being so thoughtful and thorough.

**Comment by elreydetoda** [comment]
> really! Hmm.... then clearly I'm the problem ; )

lol, not at all. I just needed some more clarity on what you're considering smaller or larger commits :sweat_smile: 

> thanks, as always, for being so thoughtful and thorough.

Anytime, thank you for being awesome! :grin:

**Comment by gerbrent** [comment]
reopening this to fix the simple E2E testing link while we wait for the remainder of https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/353 to be reviewed.

@elreydetoda : note that you'll likely need to modify #353

**Pull request merged**
