### PR TITLE
Add listing of all tags

### LINKED ISSUE #500: "Tags" url/page present no content. Regression?
> [...]the "Tags" url seems.... broken aswell. In my recollection, it used to present all tags ever present in alphabetical order, however now simply presents a "Tags" title w no content.

https://www.jupiterbroadcasting.com/tags/

_Originally posted by @gerbrent in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/497#issuecomment-1416876932_

### PR DESCRIPTION
**Pull request by ChanceM**
Closes #500. Adds list of tags to /tags url

### CODE REVIEW

**Comment by ChanceM** [comment]
Screenshot_11

**Comment by CGBassPlayer** [comment]
Is there a way to get a count of the episodes that use that tag? I'm thinking about ways to clean up the page and gaveling a count with the tag would be a nice addition. Even if you leave that code commented out for now.

Regardless, thank you for working on this. I will hopefully review it some time today

**Comment by ChanceM** [comment]
> Is there a way to get a count of the episodes that use that tag? I'm thinking about ways to clean up the page and gaveling a count with the tag would be a nice addition. Even if you leave that code commented out for now.
> 
> Regardless, thank you for working on this. I will hopefully review it some time today

Actually I had that in there and must have taken it out while playing around with it. I'll add it back.

**Comment by CGBassPlayer** [comment]
I have not looked at the code yet (only on mobile currently). If it is there, awesome, if not, just add it back in so myself or someone who actually knows website design can have that data.

**Comment by ChanceM** [comment]
image

**Review by CGBassPlayer — APPROVED** [review]
This is definitely a great start! But I think that we should open up an issue to improve the design of the page a little bit... This wall of tags can feel like a bit much when you are looking through. 

I also caught that `/tags/#yesmom` does not load. I assume it is trying to anchor itself to somewhere on the tags page that does not exist. I will reopen #534 and add this new information I have discovered.

**Comment by ChanceM** [comment]
Yeah they don't handle the # as it is technically allowed in the URL. If we manually replace with "%23" they will work. I can fix that.

**Pull request merged**
