### PR TITLE
Remove JoeRess

### PR DESCRIPTION
**Pull request by JoeRess**
PR to remove references to JoeRess from hosts/people sections of the site

### CODE REVIEW

**Comment by ChrisLAS** [comment]
Fine with the change; I can't vouch for the technical changes. But fine with deployment ✅ So I will defer to someone to review and deploy.

**Comment by CGBassPlayer** [comment]
So we can't just nuke the files of Joe as this will break old episodes of Linux Action News where he had hosted. 
image
When you click on that spot here Joe is suppose to be my brave browser gets mad and brings me to `about:blank#blocked`.

I am not sure the best course of action to remove Joe as an active host. We might be able to just update `is_archived` flag like we did with 'Friends of Jupiter Broadcasting' to get it removed from the hosts section if that is the desired outcome.

But as it stands now this should not be merged.

**Comment by JoeRess** [comment]
I'm fine with being removed from LAN episodes. Thanks. 👍

**Comment by CGBassPlayer** [comment]
Sounds good. I will most likely close this PR and replace it with my own that removes you from all the episodes in which you appear along with removing your profile.

**Comment by CGBassPlayer** [comment]
Superseded by #594

**Pull request closed without merging**
