### PR TITLE
Remove video.js Library

### LINKED ISSUE #116: vjs.zencdn.net blocked by pihole
Just wanted to give a heads up that I use a [pi-hole](https://pi-hole.net) at home, and I'm pretty sure I use [this list of block lists](https://v.firebog.net/hosts/lists.php) (the Non-crossed lists group), and that domain (vjs.zencdn.net) was getting blocked (from [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/551e71a20d01b5fa9c8b87fd7d66dbc7613c116e/themes/jb/layouts/episode/single.html#L2)).

image

So, it might be worth considering just pulling that file into the project and serving it from JB's domain instead of the other domain. That way it won't get blocked, I'm just whitelisting it on my DNS for now but something to think about for other people.

### PR DESCRIPTION
**Pull request by 1701home**
I believe I removed the call per @gerbrent in comment 3., and followed @CGBassPlayer recommendations in comment 4. Hope this helps Closes #116

### CODE REVIEW

**Comment by 1701home** [comment]
Will do more testing on my end, currently tracing the logs

**Comment by 1701home** [comment]
> Will do more testing on my end, currently tracing the logs

After looking into it, I believe there is an issue with some JS. I want to teach myself more and try to fix it. But I understand if someone else needs to take it over to complete it faster.

**Comment by CGBassPlayer** [comment]
There is a reference to videojs in the footer.html file

**Comment by 1701home** [comment]
https://www.youtube.com/watch?v=0C58ttB2-Qg

**Comment by CGBassPlayer** [comment]
Looks like the tests passed! That error was a little cryptic so I figured I'd jump in and lend a hand there. I'll review this tomorrow

**Comment by 1701home** [comment]
> Looks like the tests passed! That error was a little cryptic so I figured I'd jump in and lend a hand there. I'll review this tomorrow

Thanks as always! Want to see how many issues I can get knocked off the list.

**Review by CGBassPlayer — CHANGES_REQUESTED** [review]
Looks like there is 1 more reference to videojs and that is in the deprecated video player partial. Just need to remove `themes/jb/layouts/partials/episode/videoplayer.html`

**Comment by 1701home** [comment]
The comment with the last push tries to summarize all changes made for this PR to date. As always, feedback is always helpful.

**Review by CGBassPlayer — APPROVED** [review]
Looks like all the references are removed were removed. LGTM

**Pull request merged**
