### PR TITLE
Embed Kiwi next client

### LINKED ISSUE #316: Kiwi IRC not working properly
I'm getting ready to submit a PR for #233 and it's related issues, and I went to go test the functionality of kiwiirc.com's embed and it gave me a 502 error on the new site. So, without my PR the embed is broken (just wanted to make note of it before I submit my PR and gets merged :sweat_smile: )

image

image

From the dev tools under the `Headers` & Payload sections:
```
# General
Request URL: https://do-a.clients.kiwiirc.com/client/transport/?EIO=3&transport=polling&t=1660868636079-0
Request Method: GET
Status Code: 502 
Referrer Policy: strict-origin-when-cross-origin

# Response Headers
Connection: keep-alive
Content-Length: 568
Content-Type: text/html
Date: Fri, 19 Aug 2022 00:23:56 GMT
Server: nginx

# Request Headers
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: do-a.clients.kiwiirc.com
Origin: https://kiwiirc.com
Referer: https://kiwiirc.com/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36

# Query String Parameters
EIO: 3
transport: polling
t: 1660868636079-0
```

### PR DESCRIPTION
**Pull request by reclaimingmytime**
Closes #316 

Still need some feedback regarding the color scheme,  see https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/316#issuecomment-1220723071

### CODE REVIEW

**Comment by gerbrent** [comment]
Did some local testing and it looks good! Arguably better than the old client.. And the colour profile is fine, and didn't clash w the JB feel of the rest of the site in my opinion.

**Comment by gerbrent** [comment]
Slight change if possible:

I get a scroll bar that is nearly useless in the iframe. Possible to increase the embed size to eliminate the scroll bar?

kiwi-next scrollbar

**Comment by reclaimingmytime** [comment]
@gerbrent I don't get a scrollbar on my device (Chrome on macOS), this seems to be dependent on the OS or browser.

I increased the height by 10px, can you confirm that the scrollbar is now gone for you?

**Comment by gerbrent** [comment]
Confirmed, all is well. Feels like this is ready to merge.

**Pull request merged**
