### PR TITLE
Fix #152 - Replaced Show Artwork Images with HD Version

### LINKED ISSUE #152: Show artwork - some pixelated, fuzzy, not ideally scaled
Some of the Show artwork isn't optimally crisp. There is some artifacting from compression, some fuzzyness, lack of sharpness.

See here: https://jupiterbroadcasting.net/show/

To my eye.......

...seems great:
* [x] Extras
* [x] Office Hours

...needs work:
* [ ] LUP
* [ ] LAN
* [ ] Coder
* [ ] Self-Hosted?

image

### PR DESCRIPTION
**Pull request by simoncaron**
Quick PR to fix #152. Adding HD Artwork (pulled from Youtube thumbnails of each show).

**Before**
before

**After**
after

The only one missing is the AskNoah artwork.

### CODE REVIEW

**Comment by reesericci** [comment]
This is sorely needed. I was noticing some blurryness in the artwork while I was working on #174.

**Comment by reesericci** [comment]
Although it should really be replaced with SVG versions

**Comment by reesericci** [comment]
Actually @ChrisLAS sent AI files in the matrix chat a little bit ago:

> Let me see what I got. I do have SVGs of the MP3 art: https://www.dropbox.com/s/vob7dbm62xp3fku/JB-MP3-Cover-Art.ai?dl=0
Well. It's an Ai file... :/

> Ah here we go reesericci these are the Ai files Chz used for the website: https://www.dropbox.com/sh/q8tkicnxnenap0d/AAAXUdwQu5re3AFuMGHy2-pYa?dl=0

**Comment by simoncaron** [comment]
I found the AI files in the matrix chat and converted them to svg using Inkscape (It's missing the Office Hours artwork though...). After replacing all .png refs to .svg it's also looking pretty good!

Let me know if you prefer to stick to the 720p artwork or if we can use the converted AI files. (in which case it would be great to get the Office Hours one too!)

**Comment by gerbrent** [comment]
Shared the Office Hours artwork in Matrix (external).

**Pull request merged**
