### PR TITLE
Add Mobile Support for Live Status Indicator

### PR DESCRIPTION
**Pull request by ChanceM**
Adds a small red circle indicator to mobile menu for live status.

image

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
I will look at this later today. LOVE the feature though

**Review by CGBassPlayer — APPROVED** [review]
Sorry for the delay, had to get docker working again on my system. 

This LGTM, I tested locally during the LUP recording and it seemed to work just fine. Fantastic addition @ChanceM!

**Review by CGBassPlayer — APPROVED** [review]
Had a cache issue after reviewing. But this does still work

**Comment by gerbrent** [comment]
nice work both of you!

**Comment by elreydetoda** [comment]
This looks awesome, and I love the pulse effect you added @ChanceM!

To allow me to test this (since nothing is live right now :upside_down_face: ) I figured I'd try and get the [mocking](https://devopedia.org/mock-testing) ([we've talked about before](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/286#issuecomment-1260004920)) a try :upside_down_face:.  That way I could see what this actually looks like instead of just understanding how it works with the code :slightly_smiling_face: 

And I've got a [preliminary setup working](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/204975542e290f07caa9252149d81f1b4995128e) :grin: 

Here is just the regular (non-mobile) experience of me loading up and event I'd linked in the [smoke test issue](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/286#issuecomment-1260004920), while I'm running the test in [Playwright Debug mode](https://playwright.dev/python/docs/debug#pwdebug) (so I can stop it and debug things).

image

Then this is the addition that @ChanceM made :grin: , current I'm just setting it to mobile view in my dev tools but there's device sizes we can use to [modify the viewport](https://playwright.dev/python/docs/emulation#devices) during a test to trigger it for our actual testing.

image

We could also mock the request to the archive post as well if we want to, so that our tests don't actually rely on the jupiter.tube to be up. It sounds good in theory, but I'll probably save that for another PR :grin: 

I'll try and make a PR against your PR soon (don't know how much more I'll need to do) @ChanceM, so that we can submit tests along with this new feature :slightly_smiling_face:

**Comment by elreydetoda** [comment]
Alright, now have [mobile testing support working](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/a986a293b09b4a5d2b44d503b68f950fa7ab7f3b). Just going to build the actual test and then submit the PR :grin: 

image

**Comment by elreydetoda** [comment]
alright, I submitted [a PR](https://github.com/ChanceM/jupiterbroadcasting.com/pull/1) against your branch.  It checks for the red indicator on a regular and 3 mobile devices (not really mobile devices, but just their viewports), and saves their screenshots.

As I mentioned in the PR, it's about 95% working...the only thing not working properly is the screenshot after I expand the menu. Its getting the needed info, but it's also really wide for some reason.

Between screenshots I'm testing for the various live indicators.

Besides the tests everything else looks good to me, nice job @ChanceM :grin:

**Comment by gerbrent** [comment]
This is amazing @elreydetoda !!! Nice idea, and great execution. Gosh you're all so great!!

**Review by elreydetoda — APPROVED** [review]

**Pull request merged**
