### PR TITLE
Show Icon Updates

### LINKED ISSUE #402: Wiki icon looks like a bar code
icons

The [`fa-wikidata`](https://forkaweso.me/Fork-Awesome/icon/wikidata/) icon looks more like a [`fa-barcode`](https://forkaweso.me/Fork-Awesome/icon/barcode/) than something like a wiki.

I propose that it should either be [`fa-wikipedia-w`](https://forkaweso.me/Fork-Awesome/icon/wikipedia-w) or [`fa-book`](https://forkaweso.me/Fork-Awesome/icon/book/)

### LINKED ISSUE #403: Request: add matrix to social media buttons on each shows webpage
I noticed there are buttons for discord, Twitter, YouTube, etc, on each shows page. Perhaps it would be worth adding buttons for the associated matrix rooms to each shows web page as well?

Thanks

### PR DESCRIPTION
**Pull request by CGBassPlayer**
Fixes #402 
Fixes #403

* Replaces `fa-wikidata` icon with `fa-book` icon on show page links
* Add Links to Matrix Rooms on show pages

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
Hold off on merging this. I just saw another issue that could be combined with this

**Comment by gerbrent** [comment]
In the future, feel free to make a PR `draft` if that feels appropriate. It's a little hard to find - top right near reviewers:

image

**Comment by gerbrent** [comment]
also: gitmoji FTW! 🎉

**Comment by CGBassPlayer** [comment]
I had made the PR before I saw the issue. I don't think I can change it after the fact since I am not a collaborator

**Review by gerbrent — CHANGES_REQUESTED** [review]
would be great if these links could open in a new window/tab when clicked.

**Comment by gerbrent** [comment]
Any ideas why the LUP matrix link doesn't show a nice preview in the way the SSH, LAN, Coder rooms do? I tried to tinker w it but didn't make much progress..:

## SSH
image


## LUP
(noticed LUP has `jupiterbroadcasting.com` instead of `matrix.org` in the URL, there could be good reasons that should change...)

image

**Comment by gerbrent** [comment]
could potentially be unrelated to this PR work and more of a Matrix Room settings issue... which should then be opened as a new ticket. Depends on investigations into the matter!

**Comment by gerbrent** [comment]
Otherwise, this work as presented has been tested and works as expected (see above change request to add functionality) 👍🏻

**Comment by CGBassPlayer** [comment]
So LUP's matrix link was already implemented when I added the other shows. I will see if it is different from the reference material that is in the issue and update it if it is.

I will also add opening the links in a new tab tomorrow morning.

**Comment by gerbrent** [comment]
Yeah, I did notice LUP was already implemented, and preferred your implementation : )

**Review by gerbrent — APPROVED** [review]
looks and works well! Nicely done @CGBassPlayer

**Pull request merged**
