### PR TITLE
Issue #525

### PR DESCRIPTION
**Pull request by 1701home**
I have added the requested mastodon profile links to the host's files.

### CODE REVIEW

**Review by CGBassPlayer — CHANGES_REQUESTED** [review]
So it looks like you added the correct data to the markdown files. But we still need the HTML to render these links they are available. Currently the site does not check for mastodon links on the profile pages. But it super easy to do so!

In `themes/jb/layouts/partials/people/horizontal.html` you just need to add another if statement for the mastodon parameter you just created. It will look like this:
```html
{{ if .Params.twitter }}
  <a href="{{ .Params.twitter }}" class="card-footer-item-social" target="_blank">
    <i class="fa fa-mastodon" aria-hidden="true"></i>
  </a>
{{ end }}
```

**Review by CGBassPlayer — APPROVED** [review]
Here is the mastadon icon on the profile page with the other icons.
image

Works as expected so this LGTM.

**Comment by elreydetoda** [comment]
Thank you @1701home for your contribution and thanks @CGBassPlayer  for helping mentor them along. 🥳🚀

Waiting for the tests to run, and will merge all the way though after successes in the develop branch.

**Comment by elreydetoda** [comment]
Ah, sorry I didn't catch this before, but a small suggestion for future PRs.

@1701home in the future when you do a  PR, if you're specific addressing an already existing issue you can use the [closes keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to have it automatically close that issue upon merge.

We briefly mention it in the [contribution doc](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/develop/CONTRIBUTING.md#what-is-the-pull-request-pr-etiquette), but it isn't super apparent. That something we hope to improve with #512, but I figured I'd just mention it for if you want to contribute again 😁 thank you again for your contribution 🥳

**Comment by 1701home** [comment]
Sound good. I will read up more on it. But yes, I plan on it. I like to give back as I learn new things for my site. Thanks to JB, I'm also using Hugo+Github too. 🍻

**Comment by elreydetoda** [comment]
BTW, haven’t merged to main yet until the deploy preview finishes building, typically takes about 15 minutes. Then I'll merge to main and it'll be live 😁

Screenshot_20230317-230700_Firefox

**Comment by 1701home** [comment]
🎉🎉🎉
Big thanks to @CGBassPlayer, though. Without their hand-holding, I wasn't able to find the finish line.

**Comment by elreydetoda** [comment]
Perfect! Alright, I'll merge to main and it should be deployed in less than 5 minutes!

https://jb-deploy-prv-iac8.onrender.com/hosts/alex

**Pull request merged**
