### PR TITLE
#88 - Fixed Background Coloring in Navbar hover; Added Shows/People Dropdown options

### LINKED ISSUE #88: menu - list Guests page in menu
Currently no way to access a list of guests via navigation.

There is access to https://jupiterbroadcasting.net/guests/ if you know the URL.

### PR DESCRIPTION
**Pull request by Lord0fBytes**
Updates the work done on #100 
Resolves #88 

 In PR100 'Guests' was added as a menu item. After discussion it would be helpful to have it in a 'People' sub-menu. 
Added this functionality to this PR. 
Added the shows to a 'Shows' sub-menu

Fixed the hover background coloring in the `components/navbar.sass` file. 

Screen Shot 2022-07-18 at 12 49 35 PM
Screen Shot 2022-07-18 at 12 43 35 PM

### CODE REVIEW

**Review by StefanS-O — APPROVED** [review]

**Comment by gerbrent** [comment]
@Lord0fBytes I would love to see this PR a little more granular.

i.e. "Fixed Background Coloring in Navbar hover; Added Shows/People Dropdown options" could be usefully split into two.. in this case, to make my commenting on one of those additions a little easier.

So, I'll place this here:

I would love to see the navbar hover behaviour present less as white (inverted?) and more dark-mode friendly.. having a white block on mouse hover feel jarring to me in my all-dark-mode-everywhere environment, and also as on-click behaviour on mobile.

(fix likely in file `themes/jb/assets/css/components/navbar.sass`)

other than that, all this is great!

**Comment by gerbrent** [comment]
^ if it makes more sense to open a new issue w the above, I'm all for it!

**Comment by Lord0fBytes** [comment]
> I would love to see this PR a little more granular.
> 
> i.e. "Fixed Background Coloring in Navbar hover; Added Shows/People Dropdown options" could be usefully split into two.. in this case, to make my commenting on one of those additions a little easier.

This is good feedback. I am still getting used to using git with a team. I will be better about segmenting my commits to be more specific. 

> I would love to see the navbar hover behaviour present less as white (inverted?) and more dark-mode friendly.. having a white block on mouse hover feel jarring to me in my all-dark-mode-everywhere environment, and also as on-click behaviour on mobile.

This is easy enough to do. I was just using the default bulma settings.

**Comment by gerbrent** [comment]
> still getting used to using git with a team

same! I'm new to all this feedback and coordination, so thanks for taking it as constructive too.

**Pull request merged**
