### PR TITLE
Revamp Episode Layout

### LINKED ISSUE #226: Episode page - hosts/guests layout change
JB has suggested it would be really great to change the layout of the hosts on Episode pages. We should also consider guests in this scenario..

#### Currently
Hosts (and guests) currently occupy a large vusal weighting in the first "page" of episode pages, pushing Episode Links far down the page. 

#### Preferred
It would be great to see Hosts take less visual space to allow Episode Links to rise nearer to the top of the page. Episode Links are high priority content...

#### Suggestion
Host profiles can be made smaller, and moved to the right sidebar - below Sponsors, above Tags
Smaller Host and Guest profile cards: ...perhaps near the vertical dimensions of sponsors currently.

#### Guests - *where oh shalt thy go?*
Guests are a little more special. Hosts don't change often, so demoting their priority is quite acceptable. Guests, however, feel important indeed. What then to do?

I would love to see them in the right frame aswell, to gauge how that feels on a show like LUP w 3 hosts, and sometimes multiple guests.
Open to alternatives.

---

## [LUP 466](https://jupiterbroadcasting.net/show/linux-unplugged/466/) - 3 hosts, 1 guest

image

image

## [LUP 434](https://jupiterbroadcasting.net/show/linux-unplugged/434/) - 3 hosts, 3 guests

image

image

## [Extras 87](https://jupiterbroadcasting.net/show/jupiter-extras/87/) - 1 host, 1 guest

image

image

### PR DESCRIPTION
**Pull request by CGBassPlayer**
Fixes #226

* Shrink Hosts and Guests to a smaller image
* Implement tiles to allow vertical flow in content
* Entire Sponsor card is link instead of only the text

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
@gerbrent You had mentioned on Matrix at some point that we may want to merge these changes now and do a separate PR for moving the sponsors back up above the episode links on the mobile view. Is that something we still want to do or should I keep looking into reordering the content before marking this as ready?

**Comment by gerbrent** [comment]
Lets do them seperately. Ill merge this once i get the chance to test but otherwise looks good.. thanks!

**Comment by gerbrent** [comment]
currently getting this:
Notice the two/doubling of show artwork and `Support` button

image

**Comment by gerbrent** [comment]
The smaller host profiles look perfect! The Sponsor cards are a nice upgrade too! 💯 
There are a couple other items here that need attention:

* [ ] Titles have lost their header formatting
* [ ] Duplicate artwork and Support link

Thoughts on why those changes are occurring??

**Comment by gerbrent** [comment]
Current preview:

image

**Comment by CGBassPlayer** [comment]
The subscribe button was not there when I wrote this or submitted the PR, so I think I need to go in and remove the second support button and title card. 

I did not actually change anything up there, so I am not 100% sure why it is there, but I will fix momentarily!

**Comment by gerbrent** [comment]
This is flowing so nicely! 🎯 

image

**Comment by CGBassPlayer** [comment]
@gerbrent Should be all good now! Looks like when the subscribe button was added, Git though the code was different enough to double it.

**Comment by gerbrent** [comment]
Both issues seem fixed now on my end! 🎉 


image

**Review by gerbrent — APPROVED** [review]

**Comment by gerbrent** [comment]
Applying this to the `develop` branch to test the Gitflow workflow as discussed further in #432

**Pull request merged**
