### PR TITLE
Add hover tilt effect to the cards

### PR DESCRIPTION
**Pull request by reesericci**
I added a hover-tilt effect to the card grid on the homepage.﻿

### CODE REVIEW

**Comment by reesericci** [comment]
Screencast:
[Screencast from 07-05-2022 09:43:12 PM.webm](https://user-images.githubusercontent.com/19589006/177456879-923222cf-6486-44a0-b214-dc6d2bb64fd3.webm)

**Comment by kbondarev** [comment]
This reminds me of compiz :stuck_out_tongue_closed_eyes:
I think maybe a more subtle effect on mouse hover would be better. For example, slightly changing the background color, or adding shadows around the card to make it look like it's slightly elevated.

**Comment by kbondarev** [comment]
I agree, the less third party libraries the better.

**Comment by reesericci** [comment]
Fair enough

**Pull request closed without merging**
