### PR TITLE
Subscribe Page - Correct text description of links location

### PR DESCRIPTION
**Pull request by gerbrent**

### CODE REVIEW

**Comment by reesericci** [comment]
Can i get a screenshot or deploy preview please?

**Comment by gerbrent** [comment]
this change is just some body txt, so shouldnt be too complex..

alternatively, you could do a `git switch subscribe-txt` and built the site locally that way, as a workaround.

sufficient??

**Comment by gerbrent** [comment]
not the scraper-added show episodes, that are inadvertantly being added to this PR since I created this feature branch from an up-to-date `main` . Currently solutions being discussed in #444

**Comment by gerbrent** [comment]
# Before

image


# After

image

**Review by reesericci — APPROVED** [review]
looks good!

**Comment by elreydetoda** [comment]
You'd think after updating the develop branch it'd show you and updated "Files Changed" section...but unfortuently it doesn't for me...

image

So, just did another comparison to make sure it's only the single file @gerbrent was changing and it is... 🤦


image

**Pull request merged**
