### PR TITLE
:technologist: makefile - add `dev-build-metrics`: hugo build metrics reporting

### PR DESCRIPTION
**Pull request by gerbrent**
Added the helpful build metrics for performance reporting, if so desired. 
I'm happy to be told this isn't needed here..

### CODE REVIEW

**Comment by elreydetoda** [comment]
related #349

I think it'll be good to help with debugging situations on other machines.

**Comment by gerbrent** [comment]
Feel free to merge if you're satisfied @elreydetoda  - Look, I'm following the rules by not merging my own PRs! ; )

**Comment by gerbrent** [comment]
(though I am lobbying....)

**Review by elreydetoda — APPROVED** [review]
First off it would work perfectly fine as is. So, nicely done :grin: :partying_face: 

An enhancement you could make (definitely optional) would be to make it a bit more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), I've made [a PR](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/406) against your PR and will comment on my PR to explain the changes.

That'd be my only optional recommendation, but nicely done :grin: :partying_face:

**Comment by gerbrent** [comment]
ooo!

I don't have many DRY (new term too) skills, so this is a perfect intro. In concept, I love it and always have, in practice I don't have much experience. Love this.

**Review by elreydetoda — APPROVED** [review]
Cool, LGTM. 🥳

**Comment by gerbrent** [comment]
ooo!

I don't have many DRY (new term too) skills, so this is a perfect intro. In concept, I love it and always have, in practice I don't have much experience. Love this.

thanks for the continued mentorship @elreydetoda !

**Pull request merged**
