### PR TITLE
adding symlinks & show/<show_name>/hosts folder

### LINKED ISSUE #91: Hosts, Guests - different list pages for JB Home, Shows
We likely require for both Hosts and Guests of shows:

* [x] JB Home menu to present link to i.e. https://jupiterbroadcasting.net/hosts for ALL Hosts and i.e. https://jupiterbroadcasting.net/guests for ALL Guests on the entire network.
* [ ] Show menu to present link to i.e. Show/hosts to present all hosts of this Show only. url could be https://jupiterbroadcasting.net/show/coder-radio/hosts
* [ ] Show menu to present link to i.e. Show/guests to present all guests of this Show only. url could be https://jupiterbroadcasting.net/show/coder-radio/guests

requires #89

### PR DESCRIPTION
**Pull request by elreydetoda**
explanation here: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/91#issuecomment-1188650398

closes #91

### CODE REVIEW

**Comment by kbondarev** [comment]
@elreydetoda it looks good!
Just fix that merge conflict :)

**Comment by RealOrangeOne** [comment]
Could this not be achieved using aliases instead? Symlinks don't work at all on windows, so cloning the site there will lead to very strange build issues.

https://gohugo.io/content-management/urls/#aliases

**Comment by elreydetoda** [comment]
> Could this not be achieved using aliases instead? Symlinks don't work at all on windows, so cloning the site there will lead to very strange build issues.
> 
> https://gohugo.io/content-management/urls/#aliases

Potentially, but for now (since we know it works and are just trying to meet MVP (Minimum Viable Product) status) I'm going to just create an issue to investigate that in the future. I don't have a windows system I normally test on (I can spin up a VM), but as part of the investigation I can add in a screenshot to show it breaking things.

**Comment by elreydetoda** [comment]
alright, @kbondarev it should be good to go.

**Pull request merged**
