### PR TITLE
Revert "testing rebase breakage"

### PR DESCRIPTION
**Pull request by elreydetoda**
Reverts JupiterBroadcasting/jupiterbroadcasting.com#435

sorry thought this was open against my personal repo... 🤦

### CODE REVIEW

**Comment by gerbrent** [comment]
I believe this may have cause some deploy issue - git on the prod server was [complaining about diverging branches...](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/3155665115/jobs/5134572496#step:4:24)

We had to jump on the box, clear the local git repo and redeploy.. 
There can be methods for avoiding this in the future, since we do not really ever intend to need some git pushing functionality from the production box.

**Comment by gerbrent** [comment]
Also: pushing to `main` should have more protections. This should, in best case, not be possible to have such an error break deployments... the consequences were small this time (no update of scrapes, therefore LAN missing from production) however, I wonder if it could potentially be more problematic.

**Comment by elreydetoda** [comment]
> I believe this may have caused some deploy issue - git on the prod server was complaining about diverging branches...

That's so weird because it had 2 successful runs after that PR...

- https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/3151245985
- https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/3149008830


> We had to jump on the box, clear the local git repo and redeploy..

Just since you'd linked to it, the [`--ff-only`](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/3155665115/jobs/5134572496#step:4:30) `git config` option is the least interactive and most guaranteed to not screw things up.

> There can be methods for avoiding this in the future, since we do not really ever intend to need some git pushing functionality from the production box.

Also, another side note while I'm thinking about it, is if we'd gone with [an artifact approach](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/244#issuecomment-1220124933) to where that's the only thing the server is pulling down. It wouldn't care about these kinds of things. It just would pull down the container and keep running. It's because we're pulling down the repo on the prod server is why this git conflict error happened. Some could argue that's a feature, but I'm just giving facts about the situation 😅. my E2E PR already has the fundamentals if we wanted to use that approach since I'm already building the prod container and pushing to quay in it. Also, I'll happily jump on a call to help out get this setup if we want it.

> Also: pushing to main should have more protections.

Ya, I've outlined the branch protection we should use for main and 2 options for the develop [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/433#issuecomment-1261827926). Also @CGBassPlayer outlines where to go to add those branch protections.

**Comment by gerbrent** [comment]
> That's so weird because it had 2 successful runs after that PR...

right?! I didn't know what to make of that.......

**Comment by elreydetoda** [comment]
> > That's so weird because it had 2 successful runs after that PR...
> 
> right?! I didn't know what to make of that.......

Ya...I have no idea 😅

**Pull request merged**
