### PR TITLE
Issue #489 Navigation creating 2 unnecessary 301s

### LINKED ISSUE #489: Navigation creating 2 unnecessary 301s
### URL

https://www.jupiterbroadcasting.com

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Firefox

### Other Browser

_No response_

### Summary

The top navigation bar is forcing the browser to do 2x 301 hops to navigate to the page. This is bad for performance, but also one of the URLs in the chain is an http link, which could cause issues for some browsers today or in the near future.

To reproduce:
1. Open Dev console
2. Click on Network tab
3. Click on Boost! in the navigation at the top
4. You'll see the link points to https://www.jupiterbroadcasting.com/boost
5. When navigating to this link you are redirected to a **nonsecure** http://www.jupiterbroadcasting.com/boost/
6. This **nonsecure** URL upgrades and finally settles on https://www.jupiterbroadcasting.com/boost/

The URLs simply need to have that trailing slash added where it's missing.

### PR DESCRIPTION
**Pull request by kmogged**
Resolves #489 
Updates navigation URLs with trailing slashes
Updates hosts and people templates with trailing slashes added to the URLs
Updates Shows cookie crumb with trailing slash

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
Initial review on my phone looks good. Hopefully gonna pull it down and test locally tomorrow

**Review by CGBassPlayer — COMMENTED** [review]
So this change to links actually broke the dropdown test in our e2e testing. I am working on a figuring out the necessary changes required to get them working again and I will submit a PR against your local branch. Holding off on approval until we get that fixed.

As far as locally running the project, everything seems to be working fine and I do not see any redirects in my network tab.

**Comment by CGBassPlayer** [comment]
@kmogged I just submitted a PR to your repository to implement the changes required for the tests to pass. Once those changes are added, I will give this another look

**Comment by kmogged** [comment]
@CGBassPlayer I did a pull and quick click test and it looks good (didn't expect otherwise from your changes)

**Comment by elreydetoda** [comment]
Based on @CGBassPlayer's approval, the tests passing, and my brief view of this PR everything looks G2G (good to go). So, I'm going to merge this to develop.

Nice job @kmogged and @CGBassPlayer! :partying_face:

**Pull request merged**
