### PR TITLE
updating hugo to latest version (v0.105.0)

### PR DESCRIPTION
**Pull request by elreydetoda**
want to upgrade hugo to the latest version, mainly because of this feature we need: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/475#discussion_r1014647256

@gerbrent, don't know if we need to pull in @ironicbadger for this but the new container should just build (without any issues) and the deploy steps should be the exact same. So, I think it'll be fine to just merge this and let his build pipeline handle the rest. :grin:

here is an md file which has the changelog for all the changes between the versions. 

[summary.md](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/files/9946826/summary.md)

### CODE REVIEW

**Comment by CGBassPlayer** [comment]
Looks like in the months this has been sitting, Hugo as gone all the way to v0.110.0. I will have to look through the releases and see if there is anything new we may want or if v0.105.0 is still good for us

**Comment by gerbrent** [comment]
thanks @CGBassPlayer ! And @elreydetoda too... yes, lets get this updated if all looks good on the new version.

**Comment by elreydetoda** [comment]
BTW, for anyone that's interested I created a quick script to gather all the GH info for releases [here](https://github.com/elreydetoda/all-linux-tings/blob/master/cli_tools/changelog_summarizer/summarizer.py). The first time I decided to read the changelog I created this, because I wasn't going to go and look at every release's full release notes manually :upside_down_face:

**Comment by elreydetoda** [comment]
Here's the output from the tool:

[v0.105.0-v0.110.0_summary.md](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/files/10777268/v0.105.0-v0.110.0_summary.md)

by running:
```
./summarizer.py 'gohugoio/hugo' -c v0.105.0 -o v0.105.0-v0.110.0_summary.md
```
If you drop the `-o` stuff it'll just output to your console.

**Comment by elreydetoda** [comment]
So, there'e actually some pretty cool stuff that was released for Hugo. Mainly the [0.110.0](https://github.com/gohugoio/hugo/releases/tag/v0.110.0) & [0.109.0](https://github.com/gohugoio/hugo/releases/tag/v0.109.0) releases.

[Specifically config.toml -> hugo.toml](https://github.com/gohugoio/hugo/issues/8979) (0.110.0)
Also, they now allow you to [pass variables to SASS/SCSS](https://gohugo.io/hugo-pipes/scss-sass/#options) (0.109.0) which is awesome!

I don't think we _need_ any of that right now, but I'll create another issue for upgrading later on, mainly just want to get this merged so @CGBassPlayer can do the 404 testing stuff.

(attaching for next issue)
[v0.105.0-v0.110.0_summary.md](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/files/10777268/v0.105.0-v0.110.0_summary.md)

**Pull request merged**
